//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabicInterpretation.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Books {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Books() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabicInterpretation.Resx.Books", typeof(Books).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book1 {
            get {
                return ResourceManager.GetString("Book1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٢ صموئيل.
        /// </summary>
        public static string Book10 {
            get {
                return ResourceManager.GetString("Book10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book10Short {
            get {
                return ResourceManager.GetString("Book10Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ا أخبار الأيام.
        /// </summary>
        public static string Book11 {
            get {
                return ResourceManager.GetString("Book11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book11Short {
            get {
                return ResourceManager.GetString("Book11Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book12 {
            get {
                return ResourceManager.GetString("Book12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book12Short {
            get {
                return ResourceManager.GetString("Book12Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book13 {
            get {
                return ResourceManager.GetString("Book13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book13Short {
            get {
                return ResourceManager.GetString("Book13Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book14 {
            get {
                return ResourceManager.GetString("Book14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book14Short {
            get {
                return ResourceManager.GetString("Book14Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book15 {
            get {
                return ResourceManager.GetString("Book15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book15Short {
            get {
                return ResourceManager.GetString("Book15Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book16 {
            get {
                return ResourceManager.GetString("Book16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book16Short {
            get {
                return ResourceManager.GetString("Book16Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book17 {
            get {
                return ResourceManager.GetString("Book17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book17Short {
            get {
                return ResourceManager.GetString("Book17Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book18 {
            get {
                return ResourceManager.GetString("Book18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book18Short {
            get {
                return ResourceManager.GetString("Book18Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book19 {
            get {
                return ResourceManager.GetString("Book19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book19Short {
            get {
                return ResourceManager.GetString("Book19Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book1Short {
            get {
                return ResourceManager.GetString("Book1Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Book2 {
            get {
                return ResourceManager.GetString("Book2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book20 {
            get {
                return ResourceManager.GetString("Book20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book20Short {
            get {
                return ResourceManager.GetString("Book20Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book21 {
            get {
                return ResourceManager.GetString("Book21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book21Short {
            get {
                return ResourceManager.GetString("Book21Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book22 {
            get {
                return ResourceManager.GetString("Book22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book22Short {
            get {
                return ResourceManager.GetString("Book22Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book23 {
            get {
                return ResourceManager.GetString("Book23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book23Short {
            get {
                return ResourceManager.GetString("Book23Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book24 {
            get {
                return ResourceManager.GetString("Book24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book24Short {
            get {
                return ResourceManager.GetString("Book24Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book25 {
            get {
                return ResourceManager.GetString("Book25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book25Short {
            get {
                return ResourceManager.GetString("Book25Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book26 {
            get {
                return ResourceManager.GetString("Book26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book26Short {
            get {
                return ResourceManager.GetString("Book26Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book27 {
            get {
                return ResourceManager.GetString("Book27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book27Short {
            get {
                return ResourceManager.GetString("Book27Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book28 {
            get {
                return ResourceManager.GetString("Book28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book28Short {
            get {
                return ResourceManager.GetString("Book28Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book29 {
            get {
                return ResourceManager.GetString("Book29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book29Short {
            get {
                return ResourceManager.GetString("Book29Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خر.
        /// </summary>
        public static string Book2Short {
            get {
                return ResourceManager.GetString("Book2Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاويين.
        /// </summary>
        public static string Book3 {
            get {
                return ResourceManager.GetString("Book3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين.
        /// </summary>
        public static string Book30 {
            get {
                return ResourceManager.GetString("Book30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book30Short {
            get {
                return ResourceManager.GetString("Book30Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string Book3Short {
            get {
                return ResourceManager.GetString("Book3Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string Book4 {
            get {
                return ResourceManager.GetString("Book4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عد.
        /// </summary>
        public static string Book4Short {
            get {
                return ResourceManager.GetString("Book4Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تثنية.
        /// </summary>
        public static string Book5 {
            get {
                return ResourceManager.GetString("Book5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تث.
        /// </summary>
        public static string Book5Short {
            get {
                return ResourceManager.GetString("Book5Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يشوع.
        /// </summary>
        public static string Book6 {
            get {
                return ResourceManager.GetString("Book6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يش.
        /// </summary>
        public static string Book6Short {
            get {
                return ResourceManager.GetString("Book6Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القضاة.
        /// </summary>
        public static string Book7 {
            get {
                return ResourceManager.GetString("Book7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book7Short {
            get {
                return ResourceManager.GetString("Book7Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راعوث.
        /// </summary>
        public static string Book8 {
            get {
                return ResourceManager.GetString("Book8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book8Short {
            get {
                return ResourceManager.GetString("Book8Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ١ صموئيل.
        /// </summary>
        public static string Book9 {
            get {
                return ResourceManager.GetString("Book9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك.
        /// </summary>
        public static string Book9Short {
            get {
                return ResourceManager.GetString("Book9Short", resourceCulture);
            }
        }
    }
}
